// Doctors
export const GET_DOCTOR_LIST_SUCCESS = 'GET_DOCTOR_LIST_SUCCESS'
export const GET_DOCTOR_LIST_FAILURE = 'GET_DOCTOR_LIST_FAILURE'

export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS"
export const ADMIN_LOGIN_FAILURE = "ADMIN_LOGIN_FAILURE"

export const UPDATE_DOCTOR_STATUS_SUCCESS = 'UPDATE_DOCTOR_STATUS_SUCCESS'
export const UPDATE_DOCTOR_STATUS_FAILURE = 'UPDATE_DOCTOR_STATUS_FAILURE'